// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriorityQueueDemo.Contexts;

namespace PriorityQueueDemo.Migrations
{
    [DbContext(typeof(PriorityQueueDbContext))]
    partial class PriorityQueueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PriorityQueueDemo.Models.PriorityQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnName("end_time")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EntryTime")
                        .HasColumnName("entry_time")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrderId")
                        .HasColumnName("order_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PickTime")
                        .HasColumnName("pick_time")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("QueueTypeId")
                        .HasColumnName("queue_type_id")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("pk_priority_queue");

                    b.HasIndex("QueueTypeId")
                        .HasName("ix_priority_queue_queue_type_id");

                    b.ToTable("priority_queue");
                });

            modelBuilder.Entity("PriorityQueueDemo.Models.QueueType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Delay")
                        .HasColumnName("delay")
                        .HasColumnType("int");

                    b.Property<int?>("Duration")
                        .HasColumnName("duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id")
                        .HasName("pk_queue_type");

                    b.ToTable("queue_type");
                });

            modelBuilder.Entity("PriorityQueueDemo.Models.PriorityQueue", b =>
                {
                    b.HasOne("PriorityQueueDemo.Models.QueueType", "QueueType")
                        .WithMany("PriorityQueue")
                        .HasForeignKey("QueueTypeId")
                        .HasConstraintName("fk_priority_queue_queue_type_queue_type_id");
                });
#pragma warning restore 612, 618
        }
    }
}
