version: "3"

services:
  kpqs_mysql:
    image: mysql:5.7
    container_name: priority_queue_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - devmysqldb:/var/lib/priority_queue_db
      - ./Docker/MySQL:/docker-entrypoint-initdb.d
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      - kpqs_mysql
    stdin_open: true
    tty: true
    ports:
      - 8080:80
      - 443:443
      - 44303:44303
    environment:
     - ASPNETCORE_ENVIRONMENT=Docker
volumes:
  devmysqldb: